# Generated by Django 4.2.1 on 2023-05-27 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('genre_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('original_language', models.CharField(blank=True, max_length=50)),
                ('original_title', models.TextField(blank=True, null=True)),
                ('overview', models.TextField()),
                ('popularity', models.IntegerField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('release_date', models.CharField(blank=True, max_length=200)),
                ('title', models.TextField(blank=True)),
                ('video', models.BooleanField()),
                ('vote_average', models.IntegerField()),
                ('vote_count', models.IntegerField(blank=True)),
            ],
        ),
    ]
