# Generated by Django 4.2.1 on 2023-05-28 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fav_list', models.ManyToManyField(blank=True, null=True, related_name='favList', to='my_theater.movie')),
                ('watched_list', models.ManyToManyField(blank=True, null=True, related_name='watchedList', to='my_theater.movie')),
            ],
        ),
    ]
