# Generated by Django 4.2.1 on 2023-05-28 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_theater', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fav_list', models.ManyToManyField(blank=True, null=True, related_name='favList', to='my_theater.movie')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched_list', models.ManyToManyField(blank=True, null=True, related_name='watchedList', to='my_theater.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
