# Generated by Django 4.2.1 on 2023-05-30 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_theater', '0004_remove_profile_fav_list_remove_profile_watched_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
    ]
