# Generated by Django 4.2.1 on 2023-05-30 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_theater', '0005_alter_profile_fav_list_alter_profile_watched_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
